### ISSUE TITLE
Merge logs with RegexLogFormat

### ISSUE THREAD

**Issue by VolkDS** [sevdokimov/log-viewer#54]
I have next configuration:
logs = [
    {
        path: ${HOME}"/var/log/mymodule/*.log"
        format: {
          type: RegexLogFormat
          regex: "(?\<date\>\\d{4}-\\w{3}-\\d{2} \\d{2}:\\d{2}:\\d{2}.\\d{6}) +(?\<level\>[A-Z]+) +(?\<msg\>.+)"
          charset: UTF-8
          fields: [
            { name: "date", type: "date" },
            { name: "level", type: "level" },
            { name: "msg", type: "message" }
          ]
        }
     }
]

Directory ${HOME}/mymodule/ contains two files: 1.log and 2.log
Example of logs messages:
2021-May-28 15:46:13.461889 DEBUG   [my_app.cpp]:190       transactions=0
2021-May-28 15:46:13.462011 INFO    [my_app.cpp]:209       Loading configuration file 

When I try to access log, I see next form:

host: demo
file: /var/log/mymodule/1.log 889 bytes, 2021-05-28 15:46:14
timestamp:  N/A
offset: 0
Fields
date 2021-May-28 15:46:13.461889
level DEBUG
msg [my_app.cpp]:190	transactions=0

But when I try to merge 1.log and 2.log:
Failed to read log
/var/log/mymodule/1.log | (No date field, log cannot be merged)
/var/log/mymodule/2.log | (No date field, log cannot be merged)

How fix it?

**Comment by sevdokimov** [comment]
When you are opening several files in the same view, log-viewer needs to be able to parse timestamps for all records. You have defined the "date" field, but didn't define the format of the date. The date format must be defined explicitly for the regexp format.
Here is an example how to add the format to regexp format:
```
logs = [
    {
        path: ${HOME}"/var/log/mymodule/*.log"
        format: {
            type: RegexLogFormat
            regex: "(?<date>\\d{4}-\\w{3}-\\d{2} \\d{2}:\\d{2}:\\d{2}.\\d{6}) +(?<level>[A-Z]+) +(?<msg>.+)"
            charset: UTF-8
            dateFieldIdx: 0 // the index of the filed used as event timestamp
            datePattern: "yyyy-MMM-dd HH:mm:ss.SSS"
            fields: [
                { name: "date", type: "date" },
                { name: "level", type: "level" },
                { name: "msg", type: "message" }
            ]
        }
    }
]
```

I propose using Logback format, it is much easier:
```
logs = [
    {
        path: ${HOME}"/var/log/mymodule/*.log"
        format: {
            type: LogbackLogFormat
            pattern: "%date{yyyy-MMM-dd HH:mm:ss.SSSSSS} %level %msg%n"
        }
    }
]
```

Anyway, your log will not be shown correctly because log-viewer works unstable with timestamps containing microseconds. `2021-May-28 15:46:13.461` works, but `2021-May-28 15:46:13.461889` do not. It's a known bug: https://github.com/sevdokimov/log-viewer/issues/14

**Comment by sevdokimov** [comment]
LogViewer 0.1.7 recognizes the format of the attached log automatically, no configuration is needed. The problem with microseconds is fixed too.
